# Generated by Django 5.2.6 on 2025-09-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="sity",
            new_name="city",
        ),
    ]
