# Generated by Django 5.2.6 on 2025-10-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_sity_user_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_session_id",
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name="Checkout Session ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплата завершена"),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name="Ссылка для оплаты"),
        ),
        migrations.AddField(
            model_name="payment",
            name="price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Price ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Product ID"),
        ),
    ]
